name: Dart CI

on: [push, pull_request]

jobs:
  test-hive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-platform: [vm, chrome]
        dart-channel: [unstable]
    steps:
    - uses: actions/checkout@v1
    - name: Install Dart
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
        sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_${{ matrix.dart-channel }}.list > /etc/apt/sources.list.d/dart_${{ matrix.dart-channel }}.list'
        sudo apt-get update
        sudo apt-get install dart
    - name: Run tests
      run: |
        export PATH="$PATH:/usr/lib/dart/bin"
        pub get
        pub run test -p ${{ matrix.test-platform }}
      working-directory: hive

  test-hive_generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart-channel: [unstable]
    steps:
    - uses: actions/checkout@v1
    - name: Install Dart
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
        sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_${{ matrix.dart-channel }}.list > /etc/apt/sources.list.d/dart_${{ matrix.dart-channel }}.list'
        sudo apt-get update
        sudo apt-get install dart
    - name: Generate build_runner output
      run: |
        export PATH="$PATH:/usr/lib/dart/bin"
        pub get
        pub run build_runner build --delete-conflicting-outputs
      working-directory: hive_generator/example
  
  check-score:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hive, hive_generator, hive_flutter]
    steps:
      - uses: actions/checkout@v1
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ matrix.package }}
          minAnnotationLevel: warning
